FROM python:3.12-slim-bookworm AS base

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    PATH="/.venv/bin:$PATH"

FROM base AS uv-builder

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

COPY uv.lock pyproject.toml ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project --no-dev

FROM base

COPY --from=uv-builder /.venv /.venv

COPY backend .
COPY .env .

CMD ["python3", "-m", "app"]
