[project]
name = "agentserver"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "openai-agents[voice]>=0.2.2",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "python-socks>=2.7.1",
    "uvicorn>=0.35.0",
]
